/*
 * $Revision: 1.1 $
 * copyright (c) 2002 knowledgeTools, author: david@knowledgetools.de
 */
#include <stdio.h>
#include <db.h>
#include <errno.h>

int main(int argc, char *argv[])
{
    puts(";;;; constants.lisp generated by constants.c from db.h\n"
	 ";;;; Possibly copyright (c) 1996-2002 Sleepycat Software\n"
	 ";;;;\n"
	 ";;;; BerkeleyDB header version:\n"
	 ";;;; " DB_VERSION_STRING "\n\n"
 	 "(in-package #:berkeley-db)");

#   define doit(constant) \
        printf("(defconstant %s %d)\n", #constant, constant);

    putchar('\n');
    doit(DB_CREATE);
    doit(DB_FORCE);
    doit(DB_NOMMAP);
    doit(DB_RDONLY);
    doit(DB_RECOVER);
    doit(DB_THREAD);
    doit(DB_TRUNCATE);
    doit(DB_TXN_NOSYNC);

    putchar('\n');
    doit(DB_AUTO_COMMIT);
    doit(DB_DIRTY_READ);

    putchar('\n');
    doit(DB_CLIENT);

    putchar('\n');
    doit(DB_INIT_CDB);
    doit(DB_INIT_LOCK);
    doit(DB_INIT_LOG);
    doit(DB_INIT_MPOOL);
    doit(DB_INIT_TXN);
    doit(DB_JOINENV);
    doit(DB_LOCKDOWN);
    doit(DB_PRIVATE);
    doit(DB_RECOVER_FATAL);
    doit(DB_SYSTEM_MEM);

    putchar('\n');
    doit(DB_EXCL);

    putchar('\n');
    doit(DB_TXN_NOWAIT);
    doit(DB_TXN_SYNC);

    putchar('\n');
    doit(DB_UPGRADE);
    doit(DB_VERIFY);

    putchar('\n');
    doit(DB_ENCRYPT_AES);

    putchar('\n');
    doit(DB_CHKSUM_SHA1);
    doit(DB_DUP);
    doit(DB_DUPSORT);
    doit(DB_ENCRYPT);
    doit(DB_RECNUM);
    doit(DB_RENUMBER);
    doit(DB_REVSPLITOFF);
    doit(DB_SNAPSHOT);

    putchar('\n');
    doit(DB_LOCK_NORUN);
    doit(DB_LOCK_DEFAULT);
    doit(DB_LOCK_EXPIRE);
    doit(DB_LOCK_MAXLOCKS);
    doit(DB_LOCK_MINLOCKS);
    doit(DB_LOCK_MINWRITE);
    doit(DB_LOCK_OLDEST);
    doit(DB_LOCK_RANDOM);
    doit(DB_LOCK_YOUNGEST);

    putchar('\n');
    doit(DB_AFTER);
    doit(DB_APPEND);
    doit(DB_BEFORE);
    doit(DB_CACHED_COUNTS);
    doit(DB_COMMIT);
    doit(DB_CONSUME);
    doit(DB_CONSUME_WAIT);
    doit(DB_CURRENT);
    doit(DB_FAST_STAT);
    doit(DB_FIRST);
    doit(DB_GET_BOTH);
    doit(DB_GET_BOTHC);
    doit(DB_GET_BOTH_RANGE);
    doit(DB_GET_RECNO);
    doit(DB_JOIN_ITEM);
    doit(DB_KEYFIRST);
    doit(DB_KEYLAST);
    doit(DB_LAST);
    doit(DB_NEXT);
    doit(DB_NEXT_DUP);
    doit(DB_NEXT_NODUP);
    doit(DB_NODUPDATA);
    doit(DB_NOOVERWRITE);
    doit(DB_NOSYNC);
    doit(DB_POSITION);
    doit(DB_POSITIONI);
    doit(DB_PREV);
    doit(DB_PREV_NODUP);
    doit(DB_RECORDCOUNT);
    doit(DB_SET);
    doit(DB_SET_LOCK_TIMEOUT);
    doit(DB_SET_RANGE);
    doit(DB_SET_RECNO);
    doit(DB_SET_TXN_NOW);
    doit(DB_SET_TXN_TIMEOUT);
    doit(DB_UPDATE_SECONDARY);
    doit(DB_WRITECURSOR);
    doit(DB_WRITELOCK);

    putchar('\n');
    doit(DB_RMW);

    puts("\n;; Error codes");
    doit(DB_DONOTINDEX);
    doit(DB_KEYEMPTY);
    doit(DB_KEYEXIST);
    doit(DB_LOCK_DEADLOCK);
    doit(DB_LOCK_NOTGRANTED);
    doit(DB_NOSERVER);
    doit(DB_NOSERVER_HOME);
    doit(DB_NOSERVER_ID);
    doit(DB_NOTFOUND);
    doit(DB_OLD_VERSION);
    doit(DB_PAGE_NOTFOUND);
    doit(DB_REP_DUPMASTER);
    doit(DB_REP_HOLDELECTION);
    doit(DB_REP_NEWMASTER);
    doit(DB_REP_NEWSITE);
    doit(DB_REP_OUTDATED);
    doit(DB_REP_UNAVAIL);
    doit(DB_RUNRECOVERY);
    doit(DB_SECONDARY_BAD);
    doit(DB_VERIFY_BAD);

    putchar('\n');
    doit(EOPNOTSUPP);

    return 0;
}
