/*
 * This file has been automatically generated by cffi-grovel.
 * Do not edit it by hand.
 */

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <limits.h>
#include <time.h>
#include <stdlib.h>

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#ifndef offsetof
#define offsetof(type, slot) ((int) ((char *) &(((type *) 0)->slot)))
#endif
#define sizeofslot(type, slot) (sizeof(((type *) 0)->slot))
#define stringify(x) #x
#define indirect_stringify(x) stringify(x)

#define SIGNEDP(x) (((x)-1)<0)
#define SIGNED_(x) (SIGNEDP(x)?"":"un")
#define SIGNED64P(x) ( x <= 0x7FFFFFFFFFFFFFFFLL )

void type_name(FILE *output, int signed_p, int size);
char* print_double_for_lisp(double n);

int main(int argc, char**argv) {
  FILE *output = argc > 1 ? fopen(argv[1], "w") : stdout;
  fprintf(output, ";;;; This file has been automatically generated by "
                  "cffi-grovel.\n;;;; Do not edit it by hand.\n\n");
  fprintf(output, "(cl:in-package #:OSICAT-POSIX)\n\n");

  /* ctype section for SIZE */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "size");
  fprintf(output, " ");
  type_name(output, SIGNEDP(size_t), sizeof(size_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-size");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "size");
  fprintf(output, "))\n");

  /* ctype section for SSIZE */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "ssize");
  fprintf(output, " ");
  type_name(output, SIGNEDP(ssize_t), sizeof(ssize_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-ssize");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "ssize");
  fprintf(output, "))\n");

  /* ctype section for PID */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "pid");
  fprintf(output, " ");
  type_name(output, SIGNEDP(pid_t), sizeof(pid_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-pid");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "pid");
  fprintf(output, "))\n");

  /* ctype section for UID */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "uid");
  fprintf(output, " ");
  type_name(output, SIGNEDP(uid_t), sizeof(uid_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-uid");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "uid");
  fprintf(output, "))\n");

  /* ctype section for GID */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "gid");
  fprintf(output, " ");
  type_name(output, SIGNEDP(gid_t), sizeof(gid_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-gid");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "gid");
  fprintf(output, "))\n");

  /* ctype section for OFF */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "off");
  fprintf(output, " ");
  type_name(output, SIGNEDP(off_t), sizeof(off_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-off");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "off");
  fprintf(output, "))\n");

  /* ctype section for MODE */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "mode");
  fprintf(output, " ");
  type_name(output, SIGNEDP(mode_t), sizeof(mode_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-mode");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "mode");
  fprintf(output, "))\n");

  /* constantenum section for ERRNO-VALUES */
  fprintf(output, "(cffi:defcenum (");
  fprintf(output, "errno-values");
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eperm");
#ifdef EPERM
  fprintf(output, " ");
  fprintf(output, "%i", EPERM);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EPERM) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enoent");
#ifdef ENOENT
  fprintf(output, " ");
  fprintf(output, "%i", ENOENT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOENT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":esrch");
#ifdef ESRCH
  fprintf(output, " ");
  fprintf(output, "%i", ESRCH);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ESRCH) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eintr");
#ifdef EINTR
  fprintf(output, " ");
  fprintf(output, "%i", EINTR);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EINTR) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eio");
#ifdef EIO
  fprintf(output, " ");
  fprintf(output, "%i", EIO);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EIO) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enxio");
#ifdef ENXIO
  fprintf(output, " ");
  fprintf(output, "%i", ENXIO);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENXIO) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":e2big");
#ifdef E2BIG
  fprintf(output, " ");
  fprintf(output, "%i", E2BIG);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'E2BIG) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enoexec");
#ifdef ENOEXEC
  fprintf(output, " ");
  fprintf(output, "%i", ENOEXEC);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOEXEC) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebadf");
#ifdef EBADF
  fprintf(output, " ");
  fprintf(output, "%i", EBADF);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EBADF) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":echild");
#ifdef ECHILD
  fprintf(output, " ");
  fprintf(output, "%i", ECHILD);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ECHILD) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eagain");
#ifdef EAGAIN
  fprintf(output, " ");
  fprintf(output, "%i", EAGAIN);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EAGAIN) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enomem");
#ifdef ENOMEM
  fprintf(output, " ");
  fprintf(output, "%i", ENOMEM);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOMEM) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eacces");
#ifdef EACCES
  fprintf(output, " ");
  fprintf(output, "%i", EACCES);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EACCES) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":efault");
#ifdef EFAULT
  fprintf(output, " ");
  fprintf(output, "%i", EFAULT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EFAULT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebusy");
#ifdef EBUSY
  fprintf(output, " ");
  fprintf(output, "%i", EBUSY);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EBUSY) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eexist");
#ifdef EEXIST
  fprintf(output, " ");
  fprintf(output, "%i", EEXIST);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EEXIST) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":exdev");
#ifdef EXDEV
  fprintf(output, " ");
  fprintf(output, "%i", EXDEV);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EXDEV) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enodev");
#ifdef ENODEV
  fprintf(output, " ");
  fprintf(output, "%i", ENODEV);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENODEV) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotdir");
#ifdef ENOTDIR
  fprintf(output, " ");
  fprintf(output, "%i", ENOTDIR);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOTDIR) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eisdir");
#ifdef EISDIR
  fprintf(output, " ");
  fprintf(output, "%i", EISDIR);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EISDIR) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":einval");
#ifdef EINVAL
  fprintf(output, " ");
  fprintf(output, "%i", EINVAL);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EINVAL) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enfile");
#ifdef ENFILE
  fprintf(output, " ");
  fprintf(output, "%i", ENFILE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENFILE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":emfile");
#ifdef EMFILE
  fprintf(output, " ");
  fprintf(output, "%i", EMFILE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EMFILE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotty");
#ifdef ENOTTY
  fprintf(output, " ");
  fprintf(output, "%i", ENOTTY);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOTTY) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":efbig");
#ifdef EFBIG
  fprintf(output, " ");
  fprintf(output, "%i", EFBIG);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EFBIG) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enospc");
#ifdef ENOSPC
  fprintf(output, " ");
  fprintf(output, "%i", ENOSPC);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOSPC) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":espipe");
#ifdef ESPIPE
  fprintf(output, " ");
  fprintf(output, "%i", ESPIPE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ESPIPE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":erofs");
#ifdef EROFS
  fprintf(output, " ");
  fprintf(output, "%i", EROFS);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EROFS) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":emlink");
#ifdef EMLINK
  fprintf(output, " ");
  fprintf(output, "%i", EMLINK);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EMLINK) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":epipe");
#ifdef EPIPE
  fprintf(output, " ");
  fprintf(output, "%i", EPIPE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EPIPE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":edom");
#ifdef EDOM
  fprintf(output, " ");
  fprintf(output, "%i", EDOM);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EDOM) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":erange");
#ifdef ERANGE
  fprintf(output, " ");
  fprintf(output, "%i", ERANGE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ERANGE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":edeadlk");
#ifdef EDEADLK
  fprintf(output, " ");
  fprintf(output, "%i", EDEADLK);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EDEADLK) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enametoolong");
#ifdef ENAMETOOLONG
  fprintf(output, " ");
  fprintf(output, "%i", ENAMETOOLONG);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENAMETOOLONG) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enolck");
#ifdef ENOLCK
  fprintf(output, " ");
  fprintf(output, "%i", ENOLCK);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOLCK) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enosys");
#ifdef ENOSYS
  fprintf(output, " ");
  fprintf(output, "%i", ENOSYS);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOSYS) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotempty");
#ifdef ENOTEMPTY
  fprintf(output, " ");
  fprintf(output, "%i", ENOTEMPTY);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOTEMPTY) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":echrng");
#ifdef ECHRNG
  fprintf(output, " ");
  fprintf(output, "%i", ECHRNG);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":el2nsync");
#ifdef EL2NSYNC
  fprintf(output, " ");
  fprintf(output, "%i", EL2NSYNC);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":el3hlt");
#ifdef EL3HLT
  fprintf(output, " ");
  fprintf(output, "%i", EL3HLT);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":el3rst");
#ifdef EL3RST
  fprintf(output, " ");
  fprintf(output, "%i", EL3RST);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":elnrng");
#ifdef ELNRNG
  fprintf(output, " ");
  fprintf(output, "%i", ELNRNG);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eunatch");
#ifdef EUNATCH
  fprintf(output, " ");
  fprintf(output, "%i", EUNATCH);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enocsi");
#ifdef ENOCSI
  fprintf(output, " ");
  fprintf(output, "%i", ENOCSI);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":el2hlt");
#ifdef EL2HLT
  fprintf(output, " ");
  fprintf(output, "%i", EL2HLT);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebade");
#ifdef EBADE
  fprintf(output, " ");
  fprintf(output, "%i", EBADE);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebadr");
#ifdef EBADR
  fprintf(output, " ");
  fprintf(output, "%i", EBADR);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":exfull");
#ifdef EXFULL
  fprintf(output, " ");
  fprintf(output, "%i", EXFULL);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enoano");
#ifdef ENOANO
  fprintf(output, " ");
  fprintf(output, "%i", ENOANO);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebadrqc");
#ifdef EBADRQC
  fprintf(output, " ");
  fprintf(output, "%i", EBADRQC);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebadslt");
#ifdef EBADSLT
  fprintf(output, " ");
  fprintf(output, "%i", EBADSLT);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":edeadlock");
#ifdef EDEADLOCK
  fprintf(output, " ");
  fprintf(output, "%i", EDEADLOCK);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebfont");
#ifdef EBFONT
  fprintf(output, " ");
  fprintf(output, "%i", EBFONT);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enostr");
#ifdef ENOSTR
  fprintf(output, " ");
  fprintf(output, "%i", ENOSTR);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enodata");
#ifdef ENODATA
  fprintf(output, " ");
  fprintf(output, "%i", ENODATA);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":etime");
#ifdef ETIME
  fprintf(output, " ");
  fprintf(output, "%i", ETIME);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enosr");
#ifdef ENOSR
  fprintf(output, " ");
  fprintf(output, "%i", ENOSR);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enopkg");
#ifdef ENOPKG
  fprintf(output, " ");
  fprintf(output, "%i", ENOPKG);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eadv");
#ifdef EADV
  fprintf(output, " ");
  fprintf(output, "%i", EADV);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":esrmnt");
#ifdef ESRMNT
  fprintf(output, " ");
  fprintf(output, "%i", ESRMNT);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ecomm");
#ifdef ECOMM
  fprintf(output, " ");
  fprintf(output, "%i", ECOMM);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":edotdot");
#ifdef EDOTDOT
  fprintf(output, " ");
  fprintf(output, "%i", EDOTDOT);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotuniq");
#ifdef ENOTUNIQ
  fprintf(output, " ");
  fprintf(output, "%i", ENOTUNIQ);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebadfd");
#ifdef EBADFD
  fprintf(output, " ");
  fprintf(output, "%i", EBADFD);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eremchg");
#ifdef EREMCHG
  fprintf(output, " ");
  fprintf(output, "%i", EREMCHG);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":elibacc");
#ifdef ELIBACC
  fprintf(output, " ");
  fprintf(output, "%i", ELIBACC);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":elibbad");
#ifdef ELIBBAD
  fprintf(output, " ");
  fprintf(output, "%i", ELIBBAD);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":elibscn");
#ifdef ELIBSCN
  fprintf(output, " ");
  fprintf(output, "%i", ELIBSCN);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":elibmax");
#ifdef ELIBMAX
  fprintf(output, " ");
  fprintf(output, "%i", ELIBMAX);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":elibexec");
#ifdef ELIBEXEC
  fprintf(output, " ");
  fprintf(output, "%i", ELIBEXEC);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eilseq");
#ifdef EILSEQ
  fprintf(output, " ");
  fprintf(output, "%i", EILSEQ);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EILSEQ) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":erestart");
#ifdef ERESTART
  fprintf(output, " ");
  fprintf(output, "%i", ERESTART);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":estrpipe");
#ifdef ESTRPIPE
  fprintf(output, " ");
  fprintf(output, "%i", ESTRPIPE);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":euclean");
#ifdef EUCLEAN
  fprintf(output, " ");
  fprintf(output, "%i", EUCLEAN);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotnam");
#ifdef ENOTNAM
  fprintf(output, " ");
  fprintf(output, "%i", ENOTNAM);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enavail");
#ifdef ENAVAIL
  fprintf(output, " ");
  fprintf(output, "%i", ENAVAIL);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eremoteio");
#ifdef EREMOTEIO
  fprintf(output, " ");
  fprintf(output, "%i", EREMOTEIO);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enomedium");
#ifdef ENOMEDIUM
  fprintf(output, " ");
  fprintf(output, "%i", ENOMEDIUM);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":emediumtype");
#ifdef EMEDIUMTYPE
  fprintf(output, " ");
  fprintf(output, "%i", EMEDIUMTYPE);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":estale");
#ifdef ESTALE
  fprintf(output, " ");
  fprintf(output, "%i", ESTALE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ESTALE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotblk");
#ifdef ENOTBLK
  fprintf(output, " ");
  fprintf(output, "%i", ENOTBLK);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOTBLK) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":etxtbsy");
#ifdef ETXTBSY
  fprintf(output, " ");
  fprintf(output, "%i", ETXTBSY);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ETXTBSY) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eusers");
#ifdef EUSERS
  fprintf(output, " ");
  fprintf(output, "%i", EUSERS);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EUSERS) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eloop");
#ifdef ELOOP
  fprintf(output, " ");
  fprintf(output, "%i", ELOOP);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ELOOP) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ewouldblock");
#ifdef EWOULDBLOCK
  fprintf(output, " ");
  fprintf(output, "%i", EWOULDBLOCK);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EWOULDBLOCK) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enomsg");
#ifdef ENOMSG
  fprintf(output, " ");
  fprintf(output, "%i", ENOMSG);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOMSG) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eidrm");
#ifdef EIDRM
  fprintf(output, " ");
  fprintf(output, "%i", EIDRM);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EIDRM) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eproto");
#ifdef EPROTO
  fprintf(output, " ");
  fprintf(output, "%i", EPROTO);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EPROTO) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":emultihop");
#ifdef EMULTIHOP
  fprintf(output, " ");
  fprintf(output, "%i", EMULTIHOP);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EMULTIHOP) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ebadmsg");
#ifdef EBADMSG
  fprintf(output, " ");
  fprintf(output, "%i", EBADMSG);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EBADMSG) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eoverflow");
#ifdef EOVERFLOW
  fprintf(output, " ");
  fprintf(output, "%i", EOVERFLOW);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EOVERFLOW) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":edquot");
#ifdef EDQUOT
  fprintf(output, " ");
  fprintf(output, "%i", EDQUOT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EDQUOT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":einprogress");
#ifdef EINPROGRESS
  fprintf(output, " ");
  fprintf(output, "%i", EINPROGRESS);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EINPROGRESS) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ealready");
#ifdef EALREADY
  fprintf(output, " ");
  fprintf(output, "%i", EALREADY);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EALREADY) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eprotonosupport");
#ifdef EPROTONOSUPPORT
  fprintf(output, " ");
  fprintf(output, "%i", EPROTONOSUPPORT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EPROTONOSUPPORT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":esocktnosupport");
#ifdef ESOCKTNOSUPPORT
  fprintf(output, " ");
  fprintf(output, "%i", ESOCKTNOSUPPORT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ESOCKTNOSUPPORT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotsock");
#ifdef ENOTSOCK
  fprintf(output, " ");
  fprintf(output, "%i", ENOTSOCK);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOTSOCK) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":edestaddrreq");
#ifdef EDESTADDRREQ
  fprintf(output, " ");
  fprintf(output, "%i", EDESTADDRREQ);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EDESTADDRREQ) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":emsgsize");
#ifdef EMSGSIZE
  fprintf(output, " ");
  fprintf(output, "%i", EMSGSIZE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EMSGSIZE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eprototype");
#ifdef EPROTOTYPE
  fprintf(output, " ");
  fprintf(output, "%i", EPROTOTYPE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EPROTOTYPE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enoprotoopt");
#ifdef ENOPROTOOPT
  fprintf(output, " ");
  fprintf(output, "%i", ENOPROTOOPT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOPROTOOPT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eremote");
#ifdef EREMOTE
  fprintf(output, " ");
  fprintf(output, "%i", EREMOTE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EREMOTE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enolink");
#ifdef ENOLINK
  fprintf(output, " ");
  fprintf(output, "%i", ENOLINK);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOLINK) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":epfnosupport");
#ifdef EPFNOSUPPORT
  fprintf(output, " ");
  fprintf(output, "%i", EPFNOSUPPORT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EPFNOSUPPORT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eafnosupport");
#ifdef EAFNOSUPPORT
  fprintf(output, " ");
  fprintf(output, "%i", EAFNOSUPPORT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EAFNOSUPPORT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eaddrinuse");
#ifdef EADDRINUSE
  fprintf(output, " ");
  fprintf(output, "%i", EADDRINUSE);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EADDRINUSE) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eaddrnotavail");
#ifdef EADDRNOTAVAIL
  fprintf(output, " ");
  fprintf(output, "%i", EADDRNOTAVAIL);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EADDRNOTAVAIL) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enetdown");
#ifdef ENETDOWN
  fprintf(output, " ");
  fprintf(output, "%i", ENETDOWN);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENETDOWN) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enetunreach");
#ifdef ENETUNREACH
  fprintf(output, " ");
  fprintf(output, "%i", ENETUNREACH);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENETUNREACH) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enetreset");
#ifdef ENETRESET
  fprintf(output, " ");
  fprintf(output, "%i", ENETRESET);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENETRESET) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":econnaborted");
#ifdef ECONNABORTED
  fprintf(output, " ");
  fprintf(output, "%i", ECONNABORTED);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ECONNABORTED) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":econnreset");
#ifdef ECONNRESET
  fprintf(output, " ");
  fprintf(output, "%i", ECONNRESET);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ECONNRESET) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eisconn");
#ifdef EISCONN
  fprintf(output, " ");
  fprintf(output, "%i", EISCONN);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EISCONN) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enotconn");
#ifdef ENOTCONN
  fprintf(output, " ");
  fprintf(output, "%i", ENOTCONN);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOTCONN) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eshutdown");
#ifdef ESHUTDOWN
  fprintf(output, " ");
  fprintf(output, "%i", ESHUTDOWN);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ESHUTDOWN) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":etoomanyrefs");
#ifdef ETOOMANYREFS
  fprintf(output, " ");
  fprintf(output, "%i", ETOOMANYREFS);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ETOOMANYREFS) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":etimedout");
#ifdef ETIMEDOUT
  fprintf(output, " ");
  fprintf(output, "%i", ETIMEDOUT);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ETIMEDOUT) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":econnrefused");
#ifdef ECONNREFUSED
  fprintf(output, " ");
  fprintf(output, "%i", ECONNREFUSED);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ECONNREFUSED) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ehostdown");
#ifdef EHOSTDOWN
  fprintf(output, " ");
  fprintf(output, "%i", EHOSTDOWN);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EHOSTDOWN) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":ehostunreach");
#ifdef EHOSTUNREACH
  fprintf(output, " ");
  fprintf(output, "%i", EHOSTUNREACH);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EHOSTUNREACH) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enonet");
#ifdef ENONET
  fprintf(output, " ");
  fprintf(output, "%i", ENONET);
#else
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":enobufs");
#ifdef ENOBUFS
  fprintf(output, " ");
  fprintf(output, "%i", ENOBUFS);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'ENOBUFS) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, "\n  (");
  fprintf(output, ":eopnotsupp");
#ifdef EOPNOTSUPP
  fprintf(output, " ");
  fprintf(output, "%i", EOPNOTSUPP);
#else
  fprintf(output, "\n  #.(cl:progn (cl:warn 'cffi-grovel:missing-definition :name 'EOPNOTSUPP) -1)");
#endif
  fprintf(output, ")");
  fprintf(output, ")\n");

  /* constant section for SIGINT */
#ifdef SIGINT
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "sigint");
  fprintf(output, " ");
  if(SIGNED64P(SIGINT))
    fprintf(output, "%lli", (int64_t) SIGINT);
  else
    fprintf(output, "%llu", (uint64_t) SIGINT);
  fprintf(output, " \"interrupt program.\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SIGINT)\n");
#endif

  /* constant section for SIGILL */
#ifdef SIGILL
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "sigill");
  fprintf(output, " ");
  if(SIGNED64P(SIGILL))
    fprintf(output, "%lli", (int64_t) SIGILL);
  else
    fprintf(output, "%llu", (uint64_t) SIGILL);
  fprintf(output, " \"illegal instruction.\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SIGILL)\n");
#endif

  /* constant section for SIGABRT */
#ifdef SIGABRT
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "sigabrt");
  fprintf(output, " ");
  if(SIGNED64P(SIGABRT))
    fprintf(output, "%lli", (int64_t) SIGABRT);
  else
    fprintf(output, "%llu", (uint64_t) SIGABRT);
  fprintf(output, " \"abort program (formerly SIGIOT).\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SIGABRT)\n");
#endif

  /* constant section for SIGFPE */
#ifdef SIGFPE
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "sigfpe");
  fprintf(output, " ");
  if(SIGNED64P(SIGFPE))
    fprintf(output, "%lli", (int64_t) SIGFPE);
  else
    fprintf(output, "%llu", (uint64_t) SIGFPE);
  fprintf(output, " \"floating-point exception.\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SIGFPE)\n");
#endif

  /* constant section for SIGSEGV */
#ifdef SIGSEGV
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "sigsegv");
  fprintf(output, " ");
  if(SIGNED64P(SIGSEGV))
    fprintf(output, "%lli", (int64_t) SIGSEGV);
  else
    fprintf(output, "%llu", (uint64_t) SIGSEGV);
  fprintf(output, " \"segmentation violation.\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SIGSEGV)\n");
#endif

  /* constant section for SIGTERM */
#ifdef SIGTERM
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "sigterm");
  fprintf(output, " ");
  if(SIGNED64P(SIGTERM))
    fprintf(output, "%lli", (int64_t) SIGTERM);
  else
    fprintf(output, "%llu", (uint64_t) SIGTERM);
  fprintf(output, " \"softwareermination signal.\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SIGTERM)\n");
#endif

  /* constant section for O-RDONLY */
#ifdef O_RDONLY
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-rdonly");
  fprintf(output, " ");
  if(SIGNED64P(O_RDONLY))
    fprintf(output, "%lli", (int64_t) O_RDONLY);
  else
    fprintf(output, "%llu", (uint64_t) O_RDONLY);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-RDONLY)\n");
#endif

  /* constant section for O-WRONLY */
#ifdef O_WRONLY
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-wronly");
  fprintf(output, " ");
  if(SIGNED64P(O_WRONLY))
    fprintf(output, "%lli", (int64_t) O_WRONLY);
  else
    fprintf(output, "%llu", (uint64_t) O_WRONLY);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-WRONLY)\n");
#endif

  /* constant section for O-RDWR */
#ifdef O_RDWR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-rdwr");
  fprintf(output, " ");
  if(SIGNED64P(O_RDWR))
    fprintf(output, "%lli", (int64_t) O_RDWR);
  else
    fprintf(output, "%llu", (uint64_t) O_RDWR);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-RDWR)\n");
#endif

  /* constant section for O-CREAT */
#ifdef O_CREAT
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-creat");
  fprintf(output, " ");
  if(SIGNED64P(O_CREAT))
    fprintf(output, "%lli", (int64_t) O_CREAT);
  else
    fprintf(output, "%llu", (uint64_t) O_CREAT);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-CREAT)\n");
#endif

  /* constant section for O-EXCL */
#ifdef O_EXCL
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-excl");
  fprintf(output, " ");
  if(SIGNED64P(O_EXCL))
    fprintf(output, "%lli", (int64_t) O_EXCL);
  else
    fprintf(output, "%llu", (uint64_t) O_EXCL);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-EXCL)\n");
#endif

  /* constant section for O-TRUNC */
#ifdef O_TRUNC
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-trunc");
  fprintf(output, " ");
  if(SIGNED64P(O_TRUNC))
    fprintf(output, "%lli", (int64_t) O_TRUNC);
  else
    fprintf(output, "%llu", (uint64_t) O_TRUNC);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-TRUNC)\n");
#endif

  /* constant section for O-APPEND */
#ifdef O_APPEND
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-append");
  fprintf(output, " ");
  if(SIGNED64P(O_APPEND))
    fprintf(output, "%lli", (int64_t) O_APPEND);
  else
    fprintf(output, "%llu", (uint64_t) O_APPEND);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-APPEND)\n");
#endif

  /* constant section for O-NOCTTY */
#ifdef O_NOCTTY
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-noctty");
  fprintf(output, " ");
  if(SIGNED64P(O_NOCTTY))
    fprintf(output, "%lli", (int64_t) O_NOCTTY);
  else
    fprintf(output, "%llu", (uint64_t) O_NOCTTY);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-NOCTTY)\n");
#endif

  /* constant section for O-NONBLOCK */
#ifdef O_NONBLOCK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-nonblock");
  fprintf(output, " ");
  if(SIGNED64P(O_NONBLOCK))
    fprintf(output, "%lli", (int64_t) O_NONBLOCK);
  else
    fprintf(output, "%llu", (uint64_t) O_NONBLOCK);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-NONBLOCK)\n");
#endif

  /* constant section for O-NDELAY */
#ifdef O_NDELAY
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-ndelay");
  fprintf(output, " ");
  if(SIGNED64P(O_NDELAY))
    fprintf(output, "%lli", (int64_t) O_NDELAY);
  else
    fprintf(output, "%llu", (uint64_t) O_NDELAY);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-NDELAY)\n");
#endif

  /* constant section for O-SYNC */
#ifdef O_SYNC
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-sync");
  fprintf(output, " ");
  if(SIGNED64P(O_SYNC))
    fprintf(output, "%lli", (int64_t) O_SYNC);
  else
    fprintf(output, "%llu", (uint64_t) O_SYNC);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-SYNC)\n");
#endif

  /* constant section for O-NOFOLLOW */
#ifdef O_NOFOLLOW
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-nofollow");
  fprintf(output, " ");
  if(SIGNED64P(O_NOFOLLOW))
    fprintf(output, "%lli", (int64_t) O_NOFOLLOW);
  else
    fprintf(output, "%llu", (uint64_t) O_NOFOLLOW);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-NOFOLLOW)\n");
#endif

  /* constant section for O-ASYNC */
#ifdef O_ASYNC
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "o-async");
  fprintf(output, " ");
  if(SIGNED64P(O_ASYNC))
    fprintf(output, "%lli", (int64_t) O_ASYNC);
  else
    fprintf(output, "%llu", (uint64_t) O_ASYNC);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'O-ASYNC)\n");
#endif

  /* constant section for SEEK-SET */
#ifdef SEEK_SET
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "seek-set");
  fprintf(output, " ");
  if(SIGNED64P(SEEK_SET))
    fprintf(output, "%lli", (int64_t) SEEK_SET);
  else
    fprintf(output, "%llu", (uint64_t) SEEK_SET);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SEEK-SET)\n");
#endif

  /* constant section for SEEK-CUR */
#ifdef SEEK_CUR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "seek-cur");
  fprintf(output, " ");
  if(SIGNED64P(SEEK_CUR))
    fprintf(output, "%lli", (int64_t) SEEK_CUR);
  else
    fprintf(output, "%llu", (uint64_t) SEEK_CUR);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SEEK-CUR)\n");
#endif

  /* constant section for SEEK-END */
#ifdef SEEK_END
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "seek-end");
  fprintf(output, " ");
  if(SIGNED64P(SEEK_END))
    fprintf(output, "%lli", (int64_t) SEEK_END);
  else
    fprintf(output, "%llu", (uint64_t) SEEK_END);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'SEEK-END)\n");
#endif

  /* constant section for R-OK */
#ifdef R_OK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "r-ok");
  fprintf(output, " ");
  if(SIGNED64P(R_OK))
    fprintf(output, "%lli", (int64_t) R_OK);
  else
    fprintf(output, "%llu", (uint64_t) R_OK);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'R-OK)\n");
#endif

  /* constant section for W-OK */
#ifdef W_OK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "w-ok");
  fprintf(output, " ");
  if(SIGNED64P(W_OK))
    fprintf(output, "%lli", (int64_t) W_OK);
  else
    fprintf(output, "%llu", (uint64_t) W_OK);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'W-OK)\n");
#endif

  /* constant section for X-OK */
#ifdef X_OK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "x-ok");
  fprintf(output, " ");
  if(SIGNED64P(X_OK))
    fprintf(output, "%lli", (int64_t) X_OK);
  else
    fprintf(output, "%llu", (uint64_t) X_OK);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'X-OK)\n");
#endif

  /* constant section for F-OK */
#ifdef F_OK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "f-ok");
  fprintf(output, " ");
  if(SIGNED64P(F_OK))
    fprintf(output, "%lli", (int64_t) F_OK);
  else
    fprintf(output, "%llu", (uint64_t) F_OK);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'F-OK)\n");
#endif

  /* constant section for S-IRWXU */
#ifdef S_IRWXU
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-irwxu");
  fprintf(output, " ");
  if(SIGNED64P(S_IRWXU))
    fprintf(output, "%lli", (int64_t) S_IRWXU);
  else
    fprintf(output, "%llu", (uint64_t) S_IRWXU);
  fprintf(output, " \"read, write, execute/search by owner\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IRWXU)\n");
#endif

  /* constant section for S-IRUSR */
#ifdef S_IRUSR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-irusr");
  fprintf(output, " ");
  if(SIGNED64P(S_IRUSR))
    fprintf(output, "%lli", (int64_t) S_IRUSR);
  else
    fprintf(output, "%llu", (uint64_t) S_IRUSR);
  fprintf(output, " \"read permission, owner\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IRUSR)\n");
#endif

  /* constant section for S-IWUSR */
#ifdef S_IWUSR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iwusr");
  fprintf(output, " ");
  if(SIGNED64P(S_IWUSR))
    fprintf(output, "%lli", (int64_t) S_IWUSR);
  else
    fprintf(output, "%llu", (uint64_t) S_IWUSR);
  fprintf(output, " \"write permission, owner\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IWUSR)\n");
#endif

  /* constant section for S-IXUSR */
#ifdef S_IXUSR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ixusr");
  fprintf(output, " ");
  if(SIGNED64P(S_IXUSR))
    fprintf(output, "%lli", (int64_t) S_IXUSR);
  else
    fprintf(output, "%llu", (uint64_t) S_IXUSR);
  fprintf(output, " \"execute/search permission, owner\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IXUSR)\n");
#endif

  /* constant section for S-IFMT */
#ifdef S_IFMT
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ifmt");
  fprintf(output, " ");
  if(SIGNED64P(S_IFMT))
    fprintf(output, "%lli", (int64_t) S_IFMT);
  else
    fprintf(output, "%llu", (uint64_t) S_IFMT);
  fprintf(output, " \"bitmask for type of entry\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFMT)\n");
#endif

  /* constant section for S-IFIFO */
#ifdef S_IFIFO
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ififo");
  fprintf(output, " ");
  if(SIGNED64P(S_IFIFO))
    fprintf(output, "%lli", (int64_t) S_IFIFO);
  else
    fprintf(output, "%llu", (uint64_t) S_IFIFO);
  fprintf(output, " \"named pipe, aka fifo\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFIFO)\n");
#endif

  /* constant section for S-IFCHR */
#ifdef S_IFCHR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ifchr");
  fprintf(output, " ");
  if(SIGNED64P(S_IFCHR))
    fprintf(output, "%lli", (int64_t) S_IFCHR);
  else
    fprintf(output, "%llu", (uint64_t) S_IFCHR);
  fprintf(output, " \"special character-device\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFCHR)\n");
#endif

  /* constant section for S-IFDIR */
#ifdef S_IFDIR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ifdir");
  fprintf(output, " ");
  if(SIGNED64P(S_IFDIR))
    fprintf(output, "%lli", (int64_t) S_IFDIR);
  else
    fprintf(output, "%llu", (uint64_t) S_IFDIR);
  fprintf(output, " \"directory\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFDIR)\n");
#endif

  /* constant section for S-IFBLK */
#ifdef S_IFBLK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ifblk");
  fprintf(output, " ");
  if(SIGNED64P(S_IFBLK))
    fprintf(output, "%lli", (int64_t) S_IFBLK);
  else
    fprintf(output, "%llu", (uint64_t) S_IFBLK);
  fprintf(output, " \"special block-device\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFBLK)\n");
#endif

  /* constant section for S-IFREG */
#ifdef S_IFREG
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ifreg");
  fprintf(output, " ");
  if(SIGNED64P(S_IFREG))
    fprintf(output, "%lli", (int64_t) S_IFREG);
  else
    fprintf(output, "%llu", (uint64_t) S_IFREG);
  fprintf(output, " \"regular file\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFREG)\n");
#endif

  /* constant section for S-IFWHT */
#ifdef S_IFWHT
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ifwht");
  fprintf(output, " ");
  if(SIGNED64P(S_IFWHT))
    fprintf(output, "%lli", (int64_t) S_IFWHT);
  else
    fprintf(output, "%llu", (uint64_t) S_IFWHT);
  fprintf(output, " \"whiteout\"");
  fprintf(output, ")\n");
#else
#endif

  /* constant section for S-IREAD */
#ifdef S_IREAD
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iread");
  fprintf(output, " ");
  if(SIGNED64P(S_IREAD))
    fprintf(output, "%lli", (int64_t) S_IREAD);
  else
    fprintf(output, "%llu", (uint64_t) S_IREAD);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IREAD)\n");
#endif

  /* constant section for S-IWRITE */
#ifdef S_IWRITE
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iwrite");
  fprintf(output, " ");
  if(SIGNED64P(S_IWRITE))
    fprintf(output, "%lli", (int64_t) S_IWRITE);
  else
    fprintf(output, "%llu", (uint64_t) S_IWRITE);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IWRITE)\n");
#endif

  /* constant section for S-IEXEC */
#ifdef S_IEXEC
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iexec");
  fprintf(output, " ");
  if(SIGNED64P(S_IEXEC))
    fprintf(output, "%lli", (int64_t) S_IEXEC);
  else
    fprintf(output, "%llu", (uint64_t) S_IEXEC);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IEXEC)\n");
#endif

  /* constant section for S-IRWXG */
#ifdef S_IRWXG
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-irwxg");
  fprintf(output, " ");
  if(SIGNED64P(S_IRWXG))
    fprintf(output, "%lli", (int64_t) S_IRWXG);
  else
    fprintf(output, "%llu", (uint64_t) S_IRWXG);
  fprintf(output, " \"read, write, execute/search by group\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IRWXG)\n");
#endif

  /* constant section for S-IRGRP */
#ifdef S_IRGRP
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-irgrp");
  fprintf(output, " ");
  if(SIGNED64P(S_IRGRP))
    fprintf(output, "%lli", (int64_t) S_IRGRP);
  else
    fprintf(output, "%llu", (uint64_t) S_IRGRP);
  fprintf(output, " \"read permission, group\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IRGRP)\n");
#endif

  /* constant section for S-IWGRP */
#ifdef S_IWGRP
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iwgrp");
  fprintf(output, " ");
  if(SIGNED64P(S_IWGRP))
    fprintf(output, "%lli", (int64_t) S_IWGRP);
  else
    fprintf(output, "%llu", (uint64_t) S_IWGRP);
  fprintf(output, " \"write permission, group\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IWGRP)\n");
#endif

  /* constant section for S-IXGRP */
#ifdef S_IXGRP
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ixgrp");
  fprintf(output, " ");
  if(SIGNED64P(S_IXGRP))
    fprintf(output, "%lli", (int64_t) S_IXGRP);
  else
    fprintf(output, "%llu", (uint64_t) S_IXGRP);
  fprintf(output, " \"execute/search permission, group\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IXGRP)\n");
#endif

  /* constant section for S-IRWXO */
#ifdef S_IRWXO
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-irwxo");
  fprintf(output, " ");
  if(SIGNED64P(S_IRWXO))
    fprintf(output, "%lli", (int64_t) S_IRWXO);
  else
    fprintf(output, "%llu", (uint64_t) S_IRWXO);
  fprintf(output, " \"read, write, execute/search by others\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IRWXO)\n");
#endif

  /* constant section for S-IROTH */
#ifdef S_IROTH
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iroth");
  fprintf(output, " ");
  if(SIGNED64P(S_IROTH))
    fprintf(output, "%lli", (int64_t) S_IROTH);
  else
    fprintf(output, "%llu", (uint64_t) S_IROTH);
  fprintf(output, " \"read permission, others\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IROTH)\n");
#endif

  /* constant section for S-IWOTH */
#ifdef S_IWOTH
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iwoth");
  fprintf(output, " ");
  if(SIGNED64P(S_IWOTH))
    fprintf(output, "%lli", (int64_t) S_IWOTH);
  else
    fprintf(output, "%llu", (uint64_t) S_IWOTH);
  fprintf(output, " \"write permission, others\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IWOTH)\n");
#endif

  /* constant section for S-IXOTH */
#ifdef S_IXOTH
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ixoth");
  fprintf(output, " ");
  if(SIGNED64P(S_IXOTH))
    fprintf(output, "%lli", (int64_t) S_IXOTH);
  else
    fprintf(output, "%llu", (uint64_t) S_IXOTH);
  fprintf(output, " \"execute/search permission, others\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IXOTH)\n");
#endif

  /* constant section for S-ISUID */
#ifdef S_ISUID
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-isuid");
  fprintf(output, " ");
  if(SIGNED64P(S_ISUID))
    fprintf(output, "%lli", (int64_t) S_ISUID);
  else
    fprintf(output, "%llu", (uint64_t) S_ISUID);
  fprintf(output, " \"set-user-ID on execution\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-ISUID)\n");
#endif

  /* constant section for S-ISGID */
#ifdef S_ISGID
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-isgid");
  fprintf(output, " ");
  if(SIGNED64P(S_ISGID))
    fprintf(output, "%lli", (int64_t) S_ISGID);
  else
    fprintf(output, "%llu", (uint64_t) S_ISGID);
  fprintf(output, " \"set-group-ID on execution\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-ISGID)\n");
#endif

  /* constant section for S-ISVTX */
#ifdef S_ISVTX
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-isvtx");
  fprintf(output, " ");
  if(SIGNED64P(S_ISVTX))
    fprintf(output, "%lli", (int64_t) S_ISVTX);
  else
    fprintf(output, "%llu", (uint64_t) S_ISVTX);
  fprintf(output, " \"'sticky' bit, many meanings, nonportable\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-ISVTX)\n");
#endif

  /* constant section for S-IFLNK */
#ifdef S_IFLNK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-iflnk");
  fprintf(output, " ");
  if(SIGNED64P(S_IFLNK))
    fprintf(output, "%lli", (int64_t) S_IFLNK);
  else
    fprintf(output, "%llu", (uint64_t) S_IFLNK);
  fprintf(output, " \"symbolic link\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFLNK)\n");
#endif

  /* constant section for S-IFSOCK */
#ifdef S_IFSOCK
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "s-ifsock");
  fprintf(output, " ");
  if(SIGNED64P(S_IFSOCK))
    fprintf(output, "%lli", (int64_t) S_IFSOCK);
  else
    fprintf(output, "%llu", (uint64_t) S_IFSOCK);
  fprintf(output, " \"socket\"");
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'S-IFSOCK)\n");
#endif

  /* constant section for PATH-MAX */
#ifdef PATH_MAX
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "path-max");
  fprintf(output, " ");
  if(SIGNED64P(PATH_MAX))
    fprintf(output, "%lli", (int64_t) PATH_MAX);
  else
    fprintf(output, "%llu", (uint64_t) PATH_MAX);
  fprintf(output, ")\n");
#else
#ifdef MAXPATHLEN
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "path-max");
  fprintf(output, " ");
  if(SIGNED64P(MAXPATHLEN))
    fprintf(output, "%lli", (int64_t) MAXPATHLEN);
  else
    fprintf(output, "%llu", (uint64_t) MAXPATHLEN);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'PATH-MAX)\n");
#endif
#endif

  /* ctype section for TIME */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "time");
  fprintf(output, " ");
  type_name(output, SIGNEDP(time_t), sizeof(time_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-time");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "time");
  fprintf(output, "))\n");

  /* ctype section for DEV */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "dev");
  fprintf(output, " ");
  type_name(output, SIGNEDP(dev_t), sizeof(dev_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-dev");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "dev");
  fprintf(output, "))\n");

  /* ctype section for INO */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "ino");
  fprintf(output, " ");
  type_name(output, SIGNEDP(ino_t), sizeof(ino_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-ino");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "ino");
  fprintf(output, "))\n");

  /* ctype section for NLINK */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "nlink");
  fprintf(output, " ");
  type_name(output, SIGNEDP(nlink_t), sizeof(nlink_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-nlink");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "nlink");
  fprintf(output, "))\n");

  /* ctype section for BLKSIZE */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "blksize");
  fprintf(output, " ");
  type_name(output, SIGNEDP(blksize_t), sizeof(blksize_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-blksize");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "blksize");
  fprintf(output, "))\n");

  /* ctype section for BLKCNT */
  fprintf(output, "(cffi:defctype ");
  fprintf(output, "blkcnt");
  fprintf(output, " ");
  type_name(output, SIGNEDP(blkcnt_t), sizeof(blkcnt_t));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-blkcnt");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "blkcnt");
  fprintf(output, "))\n");

  /* cstruct section for STAT */
  fprintf(output, "(cffi:defcstruct (");
  fprintf(output, "stat");
  fprintf(output, " :size %i)", sizeof(struct stat));
  fprintf(output, "\n  (");
  fprintf(output, "dev");
  fprintf(output, " ");
  fprintf(output, "dev");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_dev));
  fprintf(output, "\n  (");
  fprintf(output, "ino");
  fprintf(output, " ");
  fprintf(output, "ino");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_ino));
  fprintf(output, "\n  (");
  fprintf(output, "mode");
  fprintf(output, " ");
  fprintf(output, "mode");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_mode));
  fprintf(output, "\n  (");
  fprintf(output, "nlink");
  fprintf(output, " ");
  fprintf(output, "nlink");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_nlink));
  fprintf(output, "\n  (");
  fprintf(output, "uid");
  fprintf(output, " ");
  fprintf(output, "uid");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_uid));
  fprintf(output, "\n  (");
  fprintf(output, "gid");
  fprintf(output, " ");
  fprintf(output, "gid");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_gid));
  fprintf(output, "\n  (");
  fprintf(output, "rdev");
  fprintf(output, " ");
  fprintf(output, "dev");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_rdev));
  fprintf(output, "\n  (");
  fprintf(output, "size");
  fprintf(output, " ");
  fprintf(output, "off");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_size));
  fprintf(output, "\n  (");
  fprintf(output, "blksize");
  fprintf(output, " ");
  fprintf(output, "blkcnt");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_blksize));
  fprintf(output, "\n  (");
  fprintf(output, "blocks");
  fprintf(output, " ");
  fprintf(output, "blksize");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_blocks));
  fprintf(output, "\n  (");
  fprintf(output, "atime");
  fprintf(output, " ");
  fprintf(output, "time");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_atime));
  fprintf(output, "\n  (");
  fprintf(output, "mtime");
  fprintf(output, " ");
  fprintf(output, "time");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_mtime));
  fprintf(output, "\n  (");
  fprintf(output, "ctime");
  fprintf(output, " ");
  fprintf(output, "time");
  fprintf(output, " :offset %i)", offsetof(struct stat, st_ctime));
  fprintf(output, ")\n");
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "size-of-stat");
  fprintf(output, " (cffi:foreign-type-size '");
  fprintf(output, "stat");
  fprintf(output, "))\n");

  if  (output != stdout)
    fclose(output);
  return 0;
}

void type_name(FILE *output, int signed_p, int size) {
  if (signed_p) {
    switch (size) {
    case 1: fprintf(output, ":int8"); break;
    case 2: fprintf(output, ":int16"); break;
    case 4: fprintf(output, ":int32"); break;
    case 8: fprintf(output, ":int64"); break;
    default: goto error;
    }
  } else {
    switch(size) {
    case 1: fprintf(output, ":uint8"); break;
    case 2: fprintf(output, ":uint16"); break;
    case 4: fprintf(output, ":uint32"); break;
    case 8: fprintf(output, ":uint64"); break;
    default: goto error;
    }
  }

  return;

error:
  fprintf(output, "(cl:error \"No type of size ~D.\" %i)\n", size);
}

char* print_double_for_lisp(double n)
{
    static char buf[256];
    memset(buf, 0, 256);
    snprintf(buf, 255, "(let ((*read-default-float-format* 'double-float)) (coerce (read-from-string \"%.20E\") 'double-float))", n);
    return buf;
}
